import time
import sys
while True:
    time.sleep(3)
    print("   ")
    print("   ")
    print("Loading...")
    print("   ")
    print("   ")
    time.sleep(3)
    trats = input("TYPE 'START' TO BEGIN ").upper()
    if trats == "START":
        time.sleep(2)
        print("   ")
        print("   ")
        print("Loading...")
        time.sleep(3)
        print("   ")
        print("   ")
        print("This here is an interactive story game. For this game, you will answer questions, some of them are multiple choice, and they will impact the story.")
        print("   ")
        print("NOTICE: TYPE THE LETTER FOR YOUR ANSWER, NOT THE ANSWER ITSELF!!!!!!")
        print("   ")
        time.sleep(6)
        print("Lets begin")
        print("   ")
        print("   ")
        time.sleep(1)
        print("Your head is pounding. You can't remember anything from the night prior. You begin to open your eyes but see nothing except the stone ceiling.")
        print("You try to move but find that you're tied down. Just then, you hear a feminine voice.")
        print("   ")
        print("'Good, you're up. I won't beat around the bush or start with theatrics so I'll just tell you. You've been kidnapped by me and my associates. You will work for us in the mines and if you do good, we'll consider releasing you.' ")
        print("   ")
        time.sleep(11)
        N1 = input("So, what's your name? ")
        if N1 == "The Helix Fossil":
            print("   ")
            time.sleep(1)
            print("...")
            time.sleep(1)
            print("...")
            time.sleep(1)
            print("...")
            time.sleep(1)
            print("'The Helix Fossil? I'm so sorry, we bow down to the almighty Helix.' You then enslave the world. YOU WIN!")
            continue
        if N1 == "Nickelodeon" or N1 == "Willimina" or N1 == "Lilo" or N1 == "Holdeenie":
            print("   ")
            time.sleep(1)
            print("Really? "+ N1 + " huh? That's actually a good name.")
            print("   ")
        else:
            print("   ")
            time.sleep(1)
            print("Really, " + N1 + "? That name is pathetic")
            print("   ")
        time.sleep(1)
        print("She cuts your binds and exits the room. You hear the clank of a lock as she closes the door.")
        print("As you get up off of the cot and begin to look around, you notice a window thats been left open and an ice pick in the corner next to a cracked wall.")
        print("   ")
        time.sleep(1)
        print("You can: ")
        time.sleep(1)
        print("A) Jump out the window.")
        time.sleep(1)
        print("B) Use the ice pick to break the wall.")
        time.sleep(1)
        choice1 = input("What do you do? ")
        print("   ")
        time.sleep(1)
        if choice1 == "a" or choice1 == "A":
            print("You jumped from the top of a tall tower. You die as soon as you hit the ground. GAME OVER")
            continue
        if choice1 == "b" or choice1 == "B":
            print("You take the ice pick and beat the wall with it until it collapses. You walk through and find yourself in a hall.")
            print("   ")
            time.sleep(1)
            print("You can:")
            time.sleep(1)
            print("A) Go left")
            time.sleep(1)
            print("B) Go right")
            time.sleep(1)
            choice2 = input("What do you do: ")
            print("   ")
            time.sleep(1)
            if choice2 == "a" or choice2 == "A" or choice2 == "b" or choice2 == "B":
                print("You begin walking, following the hall, passing multiple other cells. You arrive in a room with a guard in a chair sleeping. Next to him on a table is a dagger. Across the room is a trapdoor leading into the tunnels.")
                print("   ")
                time.sleep(1)
                print("You can: ")
                time.sleep(1)
                print("A) Go for the door")
                time.sleep(1)
                print("B) Go for the dagger and attack the guard")
                time.sleep(1)
                choice3 = input("What do you do: ")
                print("   ")
                time.sleep(1)
                if choice3 == "b" or choice3 == "B":
                    print("The guard woke up and yelled for reinforcements. You've been recaptured. GAME OVER")
                    continue
                if choice3 == "a" or choice3 == "A":
                    print("You open the trap door and descend into the tunnels. You follow the tunnels for quite some time until you come to a split in the tunnel.")
                    print("   ")
                    time.sleep(1)
                    print("You can: ")
                    time.sleep(1)
                    print("A) Go left")
                    time.sleep(1)
                    print("B) Go right")
                    time.sleep(1)
                    choice4 = input("What do you do: ")
                    print("   ")
                    time.sleep(1)
                    if choice4 == "b" or choice4 == "B":
                        print("You walk throught the tunnel and stumble into a group of bandits. They shout intruder and kill you quickly. GAME OVER")
                        continue
                    if choice4 == "a" or choice4 == "A":
                        print("You quickly sneak through the tunnel. As you get to the end, you find a door. You slowly push the door open and find it empy, so you hurry inside. You see that it's an armory, full of armor and weapons. You run quickly over to a sword that's glowing and a set of armor that looks sturdy. After taking equiping said items, you leave the room and go through the other tunnel.")
                        print("You walk throught the tunnel and stumble into a group of bandits. They prepare to attack but you fight back. You learn that the glowing sword is enchanted and it bursts into flames after drawing it. You quickly dispatch the bandits and continue walking")
                        print("As you continue, you find other pisoners in cages.")
                        print("   ")
                        time.sleep(1)
                        print("You can: ")
                        time.sleep(1)
                        print("A) Free the prisoners")
                        time.sleep(1)
                        print("B) Continue walking")
                        time.sleep(1)
                        choice5 = input("What do you do: ")
                        print("   ")
                        time.sleep(1)
                        if choice5 == "a" or choice5 == "A":
                            print("A guard above saw you and shot you in the head with his crossbow. GAME OVER")
                            continue
                        if choice5 == "b" or choice5 == "B":
                            print("You have a feeling you're being watched so you continue walking, leaving the prisoners to their fate.")
                            print("As you walk, you see the woman from before. She's ordering the lower bandits aroud, Telling them to find you")
                            print("She tells them to hurry and they all disperse. she then starts walking in the opposite direction, away from you")
                            print("You notice a door on the far wall. It appears to lead outside.")
                            print("   ")
                            time.sleep(1)
                            print("You can: ")
                            time.sleep(1)
                            print("A) Follow her")
                            time.sleep(1)
                            print("B) Go through the door")
                            time.sleep(1)
                            choice6 = input("What do you do: ")
                            print("   ")
                            time.sleep(1)
                            if choice6 == "a" or choice6 == "A":
                                print("As you follow her, you see that she appears to be injured. After following her for a while, she stumbles into a room. you go to the door, wait a few seconds and slowly open the door. you find her slumped on a bed, unconscious. after walking in, you discover that it's her bedroom.")
                                print("You see a letter on her dresser, it explains that all of the slaves here are to be killed upon the full moon to act as a blood sacrifice.")
                                print("When you turn around, you see that shes bleeding. There's a huge cut in her side, thats causing the puddle on the floor to form. You see that she'll die if you don't do something.")
                                print("   ")
                                time.sleep(1)
                                print("You can:")
                                time.sleep(1)
                                print("A) Save her")
                                time.sleep(1)
                                print("B) Leave and go though the door you saw earlier")
                                time.sleep(1)
                                choice7 = input("What do you do: ")
                                print("   ")
                                time.sleep(1)
                                if choice7 == "a" or choice7 == "A":
                                    print("You hurry to get bandages and herbs. As you stop the bleeding and dress the wound, you realize that you just saved the life of the woman who was about to kill you.")
                                    print("You hurry to leave the room and get out before you get caught again, or killed.")
                                    print("As you look around, you see an open hatch leading outside")
                                    print("   ")
                                    time.sleep(1)
                                    print("You can:")
                                    time.sleep(1)
                                    print("A) Go through the hatch")
                                    time.sleep(1)
                                    print("B) Go throught he door you saw earlier")
                                    time.sleep(1)
                                    choice8 = input("What do you do: ")
                                    print("   ")
                                    time.sleep(1)
                            if choice6 == "b" or choice6 == "B" or choice7 == "b" or choice7 == "B" or choice8 == "a" or choice8 == "A" or choice8 == "b" or choice8 == "B":
                                print("You're standing in the woods, just outside the slave encampment. You realize that if you don't leave now, you'll get caught again. You hear the sound of running water ahead of you and see a smoke stack in the distance in the other direction")
                                print("   ")
                                time.sleep(1)
                                print("You can:")
                                time.sleep(1)
                                print("A) Run towards the water")
                                time.sleep(1)
                                print("B) Head towards the smoke stack")
                                time.sleep(1)
                                choice9 = input("What do you do: ")
                                print("   ")
                                time.sleep(1)
                                if choice9 == "a" or choice9 == "A":
                                    print("You found a river. You start to follow it up stream in hopes of finding a village.")
                                if choice9 == "b" or choice9 == "B":
                                    print("As you move towards the smoke, you hear the rumblings of a village")
                                print("You found a village and quickly rush towards civilization")
                                time.sleep(1)
                                print("You have finally found the village. You see that the smoke you saw earlier is actually a bonfire in the town center")
                                print("You see a tavern to your left and a blacksmith to your right")
                                print("   ")
                                time.sleep(1)
                                print("You can:")
                                time.sleep(1)
                                print("A) Go right to the Blacksmith")
                                time.sleep(1)
                                print("B) Go left to the tavern")
                                time.sleep(1)
                                choice10 = input("What do you do: ")
                                print("   ")
                                time.sleep(1)
                                if choice10 == "a" or choice10 == "A":
                                    print("You already have a flaming sword and armor. Why're you going to the blacksmith?!? You go to the tavern instead.")
                                print("As you walk through the door and approach the counter, a man next to you says 'Hello'")
                                print("   ")
                                time.sleep(1)
                                print("You can:")
                                time.sleep(1)
                                print("A) Greet him")
                                time.sleep(1)
                                print("B) Punch him the face and start a bar fight")
                                time.sleep(1)
                                choice11 = input("What do you do: ")
                                print("   ")
                                time.sleep(1)
                                if choice11 == "b" or choice11 == "B":
                                    print("Turns out he's the village guard and doesn't enjoy gettign so he arrests you. GAME OVER")
                                    continue
                                if choice11 == "a" or choice11 == "A":
                                    print("After striking up a coversation, you learn that you're in a small trading village.")
                                    print("He tells you that fur traders from the capital come tomorrow. If you wait until then, you'll be able to get a ride there.")
                                    print("   ")
                                    time.sleep(1)
                                    print("You can:")
                                    time.sleep(1)
                                    print("A) Accept the offer")
                                    time.sleep(1)
                                    print("B) Refuse and leave the tavern")
                                    time.sleep(1)
                                    choice12 = input("What do you do: ")
                                    print("   ")
                                    time.sleep(1)
                                    if choice12 == "b" or choice12 == "B":
                                        print("As you walk out the door of the tavern, the bandits from earlier attack and kill you. GAME OVER")
                                        continue
                                    if choice12 == "a" or choice12 == "A":
                                        print("The man says that he'll bring you to the Inn. After walking out of the door, the bandits from earlier attack. But with the shariff helping you, you both kill all of the bandits.")
                                        print("He man tells you that he's the village guard and that these bandits seemed to be after you.")
                                        print("He asks you to follow him to the barracks.")
                                        print("   ")
                                        time.sleep(1)
                                        print("You can:")
                                        time.sleep(1)
                                        print("A) Try running away")
                                        time.sleep(1)
                                        print("B) Go with him")
                                        time.sleep(1)
                                        choice13 = input("What do you do: ")
                                        print("   ")
                                        time.sleep(1)
                                        if choice13 == "a" or choice13 == "A":
                                            print("You turn to run off, but you suddenly fall feeling electricity surging through your body. Not only is he the village guard, but he can also shoot lightning from his hands. GAME OVER")
                                            continue
                                        if choice13 == "b" or choice13 == "B":
                                            print("You follow him to the barracks. He offers you bread and tea")
                                            print("   ")
                                            time.sleep(1)
                                            print("You can:")
                                            time.sleep(1)
                                            print("A) Accept the food and drink")
                                            time.sleep(1)
                                            print("B) Throw it back in his face and try running")
                                            time.sleep(1)
                                            choice14 = input("What do you do: ")
                                            print("   ")
                                            time.sleep(1)
                                            if choice14 == "b" or choice13 == "B":
                                                print("You throw the food in his face and turn to run off, but you suddenly fall, feeling electricity surging through your body. Not only is he the village guard, but he can also shoot lightning from his hands. GAME OVER")
                                                continue
                                            if choice14 == "a" or choice13 == "A":
                                                print("You accept the food and tell him about your past day")
                                                print("He says that sounds like a hero origin story. You should go speak to the mage in the tower thats totally inhabitated by people, but filled with blood thirsty creature for no reason")
                                                print("Or you can stay here and get hired as a guard")
                                                print("   ")
                                                time.sleep(1)
                                                print("You can:")
                                                time.sleep(1)
                                                print("A) Do the hero stuff")
                                                time.sleep(1)
                                                print("B) Do the work stuff")
                                                time.sleep(1)
                                                choice15 = input("What do you do: ")
                                                print("   ")
                                                time.sleep(1)
                                                if choice15 == "b" or choice15 == "B":
                                                    print("That's just sad. You're in an amazing adventure and you decide to just settle down with your life. GAME OVER")
                                                    continue
                                                if choice15 == "a" or choice15 == "A":
                                                    print("Well you go do hero stuff and most likely save the world. YOU WIN")
                                                    continue
        if choice1 == "up up down down left right left right B A" or choice2 == "up up down down left right left right B A" or choice3 == "up up down down left right left right B A" or choice4 == "up up down down left right left right B A" or choice5 == "up up down down left right left right B A" or choice6 == "up up down down left right left right B A" or choice7 == "up up down down left right left right B A" or choice8 == "up up down down left right left right B A" or choice9 == "up up down down left right left right B A" or choice10 == "up up down down left right left right B A" or choice11 ==  "up up down down left right left right B A" or choice12 == "up up down down left right left right B A" or choice13 == "up up down down left right left right B A" or choice14 == "up up down down left right left right B A" or choice15 == "up up down down left right left right B A":
            print("KONAMI CODE!!!!!! You automatically win with cheats. You tripped and accidentally did the hero stuff. You saved the world " + N1 + "! Congratulations. YOU WIN")
            continue
    else:
        print("Invalid input. Exit and try again")
#Ln = 315/Col = 880(Ln280)
